query myrepo($number_of_repos: Int!) {
  viewer {
    repositories(last: $number_of_repos) {
      nodes {
        name
        url
        id
        viewerHasStarred
      }
    }
  }
  networkStatus @client {
    isConnected
  }
}
